name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kodlar
        uses: actions/checkout@v3

      - name: Build için gerekli paketler
        run: |
          sudo apt update
          sudo apt install -y build-essential ruby ruby-dev rpm
          sudo gem install --no-document fpm

      - name: C++ derlemesi yap
        run: make

      - name: Paket klasörünü hazırla
        run: |
          mkdir -p pkg/usr/local/bin
          cp bin/test pkg/usr/local/bin/

      - name: .deb ve .rpm paketlerini oluştur
        run: |
          fpm -s dir -t deb -n test -v "${GITHUB_REF_NAME}" -C pkg .
          fpm -s dir -t rpm -n test -v "${GITHUB_REF_NAME}" -C pkg .

      - name: Release oluştur ve dosyaları yükle
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            *.rpm
